# Generated by Django 5.1.7 on 2026-02-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_delete_studentachievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sport_id',
        ),
        migrations.AddField(
            model_name='student',
            name='sport_id',
            field=models.ManyToManyField(related_name='students', to='app.sport'),
        ),
    ]
